// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: messages.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
WITH messages_id AS (
    INSERT INTO messages (
        sender_id, conversation_id, type, content
    ) VALUES (
        $1, $2, $3, $4
    )
    RETURNING id
)
UPDATE conversations
SET last_message_id = (SELECT id FROM messages_id)
WHERE conversations.id = $2
RETURNING (SELECT id FROM messages_id) as message_id
`

type CreateMessageParams struct {
	SenderID int64   `json:"sender_id"`
	ID       int64   `json:"id"`
	Type     *string `json:"type"`
	Content  *string `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (int64, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.SenderID,
		arg.ID,
		arg.Type,
		arg.Content,
	)
	var message_id int64
	err := row.Scan(&message_id)
	return message_id, err
}

const getAllUnseenMessageCount = `-- name: GetAllUnseenMessageCount :many
WITH 
    clerk_users AS (
        SELECT id 
        FROM users 
        WHERE clerk_id = $1
    ),
    conv_member AS (
        SELECT conversation_id, last_seen_message_id
        FROM conversation_members 
        WHERE member_id IN (SELECT id FROM clerk_users)
    ),
    current_user_last_seen_time AS (
        SELECT conversation_id, created_at AS last_seen_time
        FROM messages
        WHERE id IN (SELECT last_seen_message_id FROM conv_member)
    )
SELECT 
    COUNT(*) AS unseen_message_count, 
    messages.conversation_id 
FROM messages
JOIN current_user_last_seen_time
    ON messages.conversation_id = current_user_last_seen_time.conversation_id
WHERE messages.created_at > current_user_last_seen_time.last_seen_time
AND messages.conversation_id IN (SELECT conversation_id FROM conv_member)
GROUP BY messages.conversation_id
`

type GetAllUnseenMessageCountRow struct {
	UnseenMessageCount int64 `json:"unseen_message_count"`
	ConversationID     int64 `json:"conversation_id"`
}

func (q *Queries) GetAllUnseenMessageCount(ctx context.Context, clerkID string) ([]GetAllUnseenMessageCountRow, error) {
	rows, err := q.db.Query(ctx, getAllUnseenMessageCount, clerkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUnseenMessageCountRow
	for rows.Next() {
		var i GetAllUnseenMessageCountRow
		if err := rows.Scan(&i.UnseenMessageCount, &i.ConversationID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConversationLastMessage = `-- name: GetConversationLastMessage :one
SELECT sender_id, users.username as sender_username, users.image_url as sender_image_url, content, type 
FROM messages
JOIN users ON users.id = sender_id
JOIN conversation_members ON conversation_members.conversation_id = messages.conversation_id
JOIN users viewer ON viewer.id = conversation_members.member_id
WHERE messages.id = $1
  AND viewer.clerk_id = $2
`

type GetConversationLastMessageParams struct {
	ID      int64  `json:"id"`
	ClerkID string `json:"clerk_id" validate:"required"`
}

type GetConversationLastMessageRow struct {
	SenderID       int64   `json:"sender_id"`
	SenderUsername string  `json:"sender_username" validate:"required,min=1,max=100"`
	SenderImageUrl *string `json:"sender_image_url" validate:"required,url"`
	Content        *string `json:"content"`
	Type           *string `json:"type"`
}

func (q *Queries) GetConversationLastMessage(ctx context.Context, arg GetConversationLastMessageParams) (GetConversationLastMessageRow, error) {
	row := q.db.QueryRow(ctx, getConversationLastMessage, arg.ID, arg.ClerkID)
	var i GetConversationLastMessageRow
	err := row.Scan(
		&i.SenderID,
		&i.SenderUsername,
		&i.SenderImageUrl,
		&i.Content,
		&i.Type,
	)
	return i, err
}

const getMessageById = `-- name: GetMessageById :one
SELECT u.id as user_id, u.username, u.image_url, u.email, m.id as message_id, m.conversation_id as conversation_id, m.type, m.content, m.created_at FROM messages m
JOIN users u ON u.id = m.sender_id
WHERE m.id = $1
`

type GetMessageByIdRow struct {
	UserID         int64              `json:"user_id"`
	Username       string             `json:"username" validate:"required,min=1,max=100"`
	ImageUrl       *string            `json:"image_url" validate:"required,url"`
	Email          string             `json:"email" validate:"required,email,max=255"`
	MessageID      int64              `json:"message_id"`
	ConversationID int64              `json:"conversation_id"`
	Type           *string            `json:"type"`
	Content        *string            `json:"content"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetMessageById(ctx context.Context, id int64) (GetMessageByIdRow, error) {
	row := q.db.QueryRow(ctx, getMessageById, id)
	var i GetMessageByIdRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.ImageUrl,
		&i.Email,
		&i.MessageID,
		&i.ConversationID,
		&i.Type,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getMessages = `-- name: GetMessages :many
SELECT u.id as user_id, u.username, u.image_url, u.email, m.id as message_id, m.conversation_id as conversation_id, m.type, m.content, m.created_at FROM messages m
JOIN users u ON u.id = m.sender_id
WHERE conversation_id = $1
ORDER BY m.created_at DESC
LIMIT $2
`

type GetMessagesParams struct {
	ConversationID int64 `json:"conversation_id"`
	Limit          int32 `json:"limit"`
}

type GetMessagesRow struct {
	UserID         int64              `json:"user_id"`
	Username       string             `json:"username" validate:"required,min=1,max=100"`
	ImageUrl       *string            `json:"image_url" validate:"required,url"`
	Email          string             `json:"email" validate:"required,email,max=255"`
	MessageID      int64              `json:"message_id"`
	ConversationID int64              `json:"conversation_id"`
	Type           *string            `json:"type"`
	Content        *string            `json:"content"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetMessages(ctx context.Context, arg GetMessagesParams) ([]GetMessagesRow, error) {
	rows, err := q.db.Query(ctx, getMessages, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesRow
	for rows.Next() {
		var i GetMessagesRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.ImageUrl,
			&i.Email,
			&i.MessageID,
			&i.ConversationID,
			&i.Type,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReadMessage = `-- name: MarkReadMessage :exec
UPDATE conversation_members AS member
SET last_seen_message_id = $3
WHERE member.conversation_id = $1
  AND member.member_id = $2
  AND $3 IS NOT NULL
  AND $3 > COALESCE(member.last_seen_message_id, 0)
  AND EXISTS (
    SELECT 1
    FROM messages
    WHERE messages.id = $3
      AND messages.conversation_id = $1
  )
`

type MarkReadMessageParams struct {
	ConversationID    int64  `json:"conversation_id"`
	MemberID          int64  `json:"member_id"`
	LastSeenMessageID *int64 `json:"last_seen_message_id"`
}

func (q *Queries) MarkReadMessage(ctx context.Context, arg MarkReadMessageParams) error {
	_, err := q.db.Exec(ctx, markReadMessage, arg.ConversationID, arg.MemberID, arg.LastSeenMessageID)
	return err
}
