// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Conversation struct {
	ID            int64              `json:"id"`
	Name          *string            `json:"name"`
	IsGroup       bool               `json:"is_group"`
	LastMessageID *int64             `json:"last_message_id"`
	GroupOwner    *int64             `json:"group_owner"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ConversationMember struct {
	ID                int64              `json:"id"`
	MemberID          int64              `json:"member_id"`
	ConversationID    int64              `json:"conversation_id"`
	LastSeenMessageID *int64             `json:"last_seen_message_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Friend struct {
	ID             int64              `json:"id"`
	UserAID        int64              `json:"user_a_id"`
	UserBID        int64              `json:"user_b_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ConversationID *int64             `json:"conversation_id"`
}

type FriendRequest struct {
	ID         int64              `json:"id"`
	SenderID   int64              `json:"sender_id" validate:"required"`
	ReceiverID int64              `json:"receiver_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Message struct {
	ID             int64              `json:"id"`
	SenderID       int64              `json:"sender_id"`
	ConversationID int64              `json:"conversation_id"`
	Type           *string            `json:"type"`
	Content        *string            `json:"content"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type NotificationDelivery struct {
	ID             int64              `json:"id"`
	EventID        int64              `json:"event_id"`
	MessageID      int64              `json:"message_id"`
	RecipientID    int64              `json:"recipient_id"`
	SubscriptionID int64              `json:"subscription_id"`
	Channel        string             `json:"channel"`
	Status         string             `json:"status"`
	Attempts       int32              `json:"attempts"`
	AvailableAt    pgtype.Timestamptz `json:"available_at"`
	LockedAt       pgtype.Timestamptz `json:"locked_at"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
	LastError      *string            `json:"last_error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type OutboxEvent struct {
	ID            int64              `json:"id"`
	EventType     string             `json:"event_type"`
	EventVersion  int32              `json:"event_version"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   int64              `json:"aggregate_id"`
	Payload       []byte             `json:"payload"`
	Status        string             `json:"status"`
	Attempts      int32              `json:"attempts"`
	AvailableAt   pgtype.Timestamptz `json:"available_at"`
	LockedAt      pgtype.Timestamptz `json:"locked_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	LastError     *string            `json:"last_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type PushSubscription struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	Endpoint    string             `json:"endpoint"`
	P256dh      string             `json:"p256dh"`
	Auth        string             `json:"auth"`
	UserAgent   *string            `json:"user_agent"`
	DeviceLabel *string            `json:"device_label"`
	Enabled     bool               `json:"enabled"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	DisabledAt  pgtype.Timestamptz `json:"disabled_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID        int64              `json:"id"`
	Username  string             `json:"username" validate:"required,min=1,max=100"`
	Email     string             `json:"email" validate:"required,email,max=255"`
	ClerkID   string             `json:"clerk_id" validate:"required"`
	ImageUrl  *string            `json:"image_url" validate:"required,url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
