// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: notification_deliveries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertNotificationDelivery = `-- name: InsertNotificationDelivery :exec
-- RabbitMQ provides at-least-once delivery. A conflict means this exact
-- event/recipient/subscription combination has already been scheduled and is
-- therefore a successful idempotent operation.
INSERT INTO notification_deliveries (
    event_id,
    message_id,
    recipient_id,
    subscription_id,
    channel
)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (event_id, recipient_id, subscription_id, channel) DO NOTHING
`

type InsertNotificationDeliveryParams struct {
	EventID        int64  `json:"event_id"`
	MessageID      int64  `json:"message_id"`
	RecipientID    int64  `json:"recipient_id"`
	SubscriptionID int64  `json:"subscription_id"`
	Channel        string `json:"channel"`
}

func (q *Queries) InsertNotificationDelivery(ctx context.Context, arg InsertNotificationDeliveryParams) error {
	_, err := q.db.Exec(ctx, insertNotificationDelivery,
		arg.EventID,
		arg.MessageID,
		arg.RecipientID,
		arg.SubscriptionID,
		arg.Channel,
	)
	return err
}

const claimNotificationDeliveries = `-- name: ClaimNotificationDeliveries :many
-- Lease a bounded batch so multiple delivery workers can operate concurrently
-- without sending the same row at the same time. A stale processing lease is
-- eligible again after five minutes when a worker crashes.
WITH candidates AS (
    SELECT id
    FROM notification_deliveries
    WHERE (
        status = 'pending'
        AND available_at <= NOW()
    ) OR (
        status = 'processing'
        AND locked_at < NOW() - INTERVAL '5 minutes'
    )
    ORDER BY id
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
UPDATE notification_deliveries AS delivery
SET
    status = 'processing',
    attempts = delivery.attempts + 1,
    locked_at = NOW(),
    updated_at = NOW()
FROM candidates
WHERE delivery.id = candidates.id
RETURNING
    delivery.id,
    delivery.event_id,
    delivery.message_id,
    delivery.recipient_id,
    delivery.subscription_id,
    delivery.channel,
    delivery.attempts,
    delivery.created_at
`

type ClaimNotificationDeliveriesRow struct {
	ID             int64              `json:"id"`
	EventID        int64              `json:"event_id"`
	MessageID      int64              `json:"message_id"`
	RecipientID    int64              `json:"recipient_id"`
	SubscriptionID int64              `json:"subscription_id"`
	Channel        string             `json:"channel"`
	Attempts       int32              `json:"attempts"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ClaimNotificationDeliveries(ctx context.Context, limit int32) ([]ClaimNotificationDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, claimNotificationDeliveries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimNotificationDeliveriesRow
	for rows.Next() {
		var i ClaimNotificationDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.MessageID,
			&i.RecipientID,
			&i.SubscriptionID,
			&i.Channel,
			&i.Attempts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationDelivery = `-- name: GetNotificationDelivery :one
-- The subscription is read after claiming the delivery. Joining here keeps
-- endpoint credentials out of the queue event and lets disabled endpoints be
-- skipped without contacting a push provider.
SELECT
    delivery.id,
    delivery.event_id,
    delivery.message_id,
    delivery.recipient_id,
    delivery.subscription_id,
    delivery.channel,
    delivery.attempts,
    delivery.created_at,
    subscription.endpoint,
    subscription.p256dh,
    subscription.auth,
    subscription.enabled
FROM notification_deliveries AS delivery
LEFT JOIN push_subscriptions AS subscription
  ON subscription.id = delivery.subscription_id
WHERE delivery.id = $1
`

type GetNotificationDeliveryRow struct {
	ID             int64              `json:"id"`
	EventID        int64              `json:"event_id"`
	MessageID      int64              `json:"message_id"`
	RecipientID    int64              `json:"recipient_id"`
	SubscriptionID int64              `json:"subscription_id"`
	Channel        string             `json:"channel"`
	Attempts       int32              `json:"attempts"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Endpoint       *string            `json:"endpoint"`
	P256dh         *string            `json:"p256dh"`
	Auth           *string            `json:"auth"`
	Enabled        *bool              `json:"enabled"`
}

func (q *Queries) GetNotificationDelivery(ctx context.Context, id int64) (GetNotificationDeliveryRow, error) {
	row := q.db.QueryRow(ctx, getNotificationDelivery, id)
	var i GetNotificationDeliveryRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.MessageID,
		&i.RecipientID,
		&i.SubscriptionID,
		&i.Channel,
		&i.Attempts,
		&i.CreatedAt,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
		&i.Enabled,
	)
	return i, err
}

const markNotificationDeliveryFailed = `-- name: MarkNotificationDeliveryFailed :exec
-- The worker supplies the next status and retry delay. Permanent failures use
-- skipped or failed with a zero delay and remain inspectable.
UPDATE notification_deliveries
SET
    status = $2,
    available_at = NOW() + ($3::integer * INTERVAL '1 second'),
    locked_at = NULL,
    last_error = $4,
    updated_at = NOW()
WHERE id = $1
`

type MarkNotificationDeliveryFailedParams struct {
	ID               int64   `json:"id"`
	Status           string  `json:"status"`
	RetryAfterSecond int32   `json:"retry_after_second"`
	LastError        *string `json:"last_error"`
}

func (q *Queries) MarkNotificationDeliveryFailed(ctx context.Context, arg MarkNotificationDeliveryFailedParams) error {
	_, err := q.db.Exec(ctx, markNotificationDeliveryFailed,
		arg.ID,
		arg.Status,
		arg.RetryAfterSecond,
		arg.LastError,
	)
	return err
}

const markNotificationDeliverySent = `-- name: MarkNotificationDeliverySent :exec
UPDATE notification_deliveries
SET
    status = 'sent',
    sent_at = NOW(),
    locked_at = NULL,
    last_error = NULL,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkNotificationDeliverySent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markNotificationDeliverySent, id)
	return err
}
