// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: outbox.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimOutboxEvents = `-- name: ClaimOutboxEvents :many
WITH candidates AS (
    SELECT id
    FROM outbox_events
    WHERE (
        status = 'pending'
        AND available_at <= NOW()
    ) OR (
        status = 'processing'
        AND locked_at < NOW() - INTERVAL '5 minutes'
    )
    ORDER BY id
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
UPDATE outbox_events AS event
SET
    status = 'processing',
    attempts = event.attempts + 1,
    locked_at = NOW()
FROM candidates
WHERE event.id = candidates.id
RETURNING
    event.id,
    event.event_type,
    event.event_version,
    event.aggregate_type,
    event.aggregate_id,
    event.payload,
    event.attempts,
    event.created_at
`

type ClaimOutboxEventsRow struct {
	ID            int64              `json:"id"`
	EventType     string             `json:"event_type"`
	EventVersion  int32              `json:"event_version"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   int64              `json:"aggregate_id"`
	Payload       []byte             `json:"payload"`
	Attempts      int32              `json:"attempts"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

// Claim a bounded batch with row locks. SKIP LOCKED lets multiple API
// instances run workers concurrently without waiting on one another, while
// the lease condition recovers rows from a worker that crashed mid-publish.
func (q *Queries) ClaimOutboxEvents(ctx context.Context, limit int32) ([]ClaimOutboxEventsRow, error) {
	rows, err := q.db.Query(ctx, claimOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimOutboxEventsRow
	for rows.Next() {
		var i ClaimOutboxEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.EventVersion,
			&i.AggregateType,
			&i.AggregateID,
			&i.Payload,
			&i.Attempts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventFailed = `-- name: MarkOutboxEventFailed :exec
UPDATE outbox_events
SET
    status = $1,
    available_at = NOW() + ($2::integer * INTERVAL '1 second'),
    locked_at = NULL,
    last_error = $3
WHERE id = $4
`

type MarkOutboxEventFailedParams struct {
	Status           string  `json:"status"`
	RetryAfterSecond int32   `json:"retry_after_second"`
	LastError        *string `json:"last_error"`
	ID               int64   `json:"id"`
}

// The worker chooses the next status and retry time. Keeping this update
// generic allows transient failures to return to pending while exhausted
// events can be retained as failed records for operational inspection.
func (q *Queries) MarkOutboxEventFailed(ctx context.Context, arg MarkOutboxEventFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxEventFailed,
		arg.Status,
		arg.RetryAfterSecond,
		arg.LastError,
		arg.ID,
	)
	return err
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :exec
UPDATE outbox_events
SET
    status = 'published',
    published_at = NOW(),
    locked_at = NULL,
    last_error = NULL
WHERE id = $1
`

// A successful publisher confirmation is the only point at which an event
// becomes published. The row remains for auditability and deduplication.
func (q *Queries) MarkOutboxEventPublished(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markOutboxEventPublished, id)
	return err
}
