// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: push_subscriptions.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertPushSubscription = `-- name: UpsertPushSubscription :one
-- Registering the same browser subscription repeatedly is safe. If a browser
-- logs out and another user later signs in on it, ownership is transferred
-- only through this authenticated endpoint and the old disabled state is
-- cleared for the new delivery owner.
INSERT INTO push_subscriptions (
    user_id,
    endpoint,
    p256dh,
    auth,
    user_agent,
    device_label,
    enabled,
    disabled_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, true, NULL, NOW())
ON CONFLICT (endpoint) DO UPDATE SET
    user_id = EXCLUDED.user_id,
    p256dh = EXCLUDED.p256dh,
    auth = EXCLUDED.auth,
    user_agent = EXCLUDED.user_agent,
    device_label = EXCLUDED.device_label,
    enabled = true,
    disabled_at = NULL,
    updated_at = NOW()
RETURNING
    id,
    user_id,
    endpoint,
    p256dh,
    auth,
    user_agent,
    device_label,
    enabled,
    last_used_at,
    disabled_at,
    created_at,
    updated_at
`

type UpsertPushSubscriptionParams struct {
	UserID      int64   `json:"user_id"`
	Endpoint    string  `json:"endpoint"`
	P256dh      string  `json:"p256dh"`
	Auth        string  `json:"auth"`
	UserAgent   *string `json:"user_agent"`
	DeviceLabel *string `json:"device_label"`
}

type UpsertPushSubscriptionRow struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	Endpoint    string             `json:"endpoint"`
	P256dh      string             `json:"p256dh"`
	Auth        string             `json:"auth"`
	UserAgent   *string            `json:"user_agent"`
	DeviceLabel *string            `json:"device_label"`
	Enabled     bool               `json:"enabled"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	DisabledAt  pgtype.Timestamptz `json:"disabled_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertPushSubscription(ctx context.Context, arg UpsertPushSubscriptionParams) (UpsertPushSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, upsertPushSubscription,
		arg.UserID,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
		arg.UserAgent,
		arg.DeviceLabel,
	)
	var i UpsertPushSubscriptionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
		&i.UserAgent,
		&i.DeviceLabel,
		&i.Enabled,
		&i.LastUsedAt,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnabledPushSubscriptions = `-- name: GetEnabledPushSubscriptions :many
-- The notification consumer only needs currently enabled endpoints. Disabled
-- rows remain available for auditing and are excluded at the database layer.
SELECT
    id,
    user_id,
    endpoint,
    p256dh,
    auth,
    user_agent,
    device_label,
    enabled,
    last_used_at,
    disabled_at,
    created_at,
    updated_at
FROM push_subscriptions
WHERE user_id = $1
  AND enabled = true
ORDER BY id
`

type GetEnabledPushSubscriptionsRow struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	Endpoint    string             `json:"endpoint"`
	P256dh      string             `json:"p256dh"`
	Auth        string             `json:"auth"`
	UserAgent   *string            `json:"user_agent"`
	DeviceLabel *string            `json:"device_label"`
	Enabled     bool               `json:"enabled"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	DisabledAt  pgtype.Timestamptz `json:"disabled_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetEnabledPushSubscriptions(ctx context.Context, userID int64) ([]GetEnabledPushSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, getEnabledPushSubscriptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEnabledPushSubscriptionsRow
	for rows.Next() {
		var i GetEnabledPushSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.UserAgent,
			&i.DeviceLabel,
			&i.Enabled,
			&i.LastUsedAt,
			&i.DisabledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const disablePushSubscription = `-- name: DisablePushSubscription :exec
-- Ownership is part of the predicate so one user cannot disable another
-- user's browser endpoint even if an ID is guessed.
UPDATE push_subscriptions
SET
    enabled = false,
    disabled_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND user_id = $2
`

type DisablePushSubscriptionParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DisablePushSubscription(ctx context.Context, arg DisablePushSubscriptionParams) error {
	_, err := q.db.Exec(ctx, disablePushSubscription, arg.ID, arg.UserID)
	return err
}

const disablePushSubscriptionByEndpoint = `-- name: DisablePushSubscriptionByEndpoint :exec
-- Push providers commonly identify an invalid subscription by endpoint. This
-- operation is intentionally scoped to the endpoint and can be called by the
-- trusted delivery worker after a permanent provider response.
UPDATE push_subscriptions
SET
    enabled = false,
    disabled_at = NOW(),
    updated_at = NOW()
WHERE endpoint = $1
`

func (q *Queries) DisablePushSubscriptionByEndpoint(ctx context.Context, endpoint string) error {
	_, err := q.db.Exec(ctx, disablePushSubscriptionByEndpoint, endpoint)
	return err
}

const markPushSubscriptionUsed = `-- name: MarkPushSubscriptionUsed :exec
UPDATE push_subscriptions
SET
    last_used_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkPushSubscriptionUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markPushSubscriptionUsed, id)
	return err
}
